# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SegmentadorOlivos
                                 A QGIS plugin
 Segments olive tree canopies in orthophotos using the Otsu method.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-03
        copyright            : (C) 2025 by Cristian AI Agro
        email                : cristianquevedoagro@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SegmentadorOlivos class from file SegmentadorOlivos.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .segmentador_olivos import SegmentadorOlivos
    return SegmentadorOlivos(iface)
